/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    supplements: Supplement;
    results: Result;
    'research-papers': ResearchPaper;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    supplements: SupplementsSelect<false> | SupplementsSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    'research-papers': ResearchPapersSelect<false> | ResearchPapersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplements".
 */
export interface Supplement {
  id: number;
  name: string;
  dosage?: {
    cortisol?: number | null;
    inflammation?: number | null;
    muscleDamage?: number | null;
    muscleSoreness?: number | null;
    oxidativeStress?: number | null;
    pain?: number | null;
    sleepQuality?: number | null;
  };
  gradeScore?: {
    cortisol?: string | null;
    inflammation?: string | null;
    muscleDamage?: string | null;
    muscleSoreness?: string | null;
    oxidativeStress?: string | null;
    pain?: string | null;
    sleepQuality?: string | null;
  };
  linearScore?: {
    cortisol?: number | null;
    inflammation?: number | null;
    muscleDamage?: number | null;
    muscleSoreness?: number | null;
    oxidativeStress?: number | null;
    pain?: number | null;
    sleepQuality?: number | null;
  };
  maxValues?: {
    cortisol?: number | null;
    inflammation?: number | null;
    muscleDamage?: number | null;
    muscleSoreness?: number | null;
    oxidativeStress?: number | null;
    pain?: number | null;
    sleepQuality?: number | null;
  };
  sumValues?: {
    cortisol?: number | null;
    inflammation?: number | null;
    muscleDamage?: number | null;
    muscleSoreness?: number | null;
    oxidativeStress?: number | null;
    pain?: number | null;
    sleepQuality?: number | null;
  };
  tldr?: {
    cortisol?: string | null;
    inflammation?: string | null;
    muscleDamage?: string | null;
    muscleSoreness?: string | null;
    oxidativeStress?: string | null;
    pain?: string | null;
    sleepQuality?: string | null;
  };
  results?: (number | Result)[] | null;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  product: string;
  supplement: number | Supplement;
  researchPaper?: (number | null) | ResearchPaper;
  mainTag?: string | null;
  subTag?: string | null;
  benefit?: string | null;
  benefitValue?: number | null;
  oxidativeStressFilter?: boolean | null;
  muscleDamageFilter?: boolean | null;
  muscleSorenessFilter?: boolean | null;
  inflammationFilter?: boolean | null;
  painFilter?: boolean | null;
  sleepQualityFilter?: boolean | null;
  cortisolFilter?: boolean | null;
  cortisolCleaning?: boolean | null;
  score?: number | null;
  participants?: number | null;
  age?: number | null;
  maxPain?: number | null;
  year?: number | null;
  sex?: string | null;
  bodyType?: string | null;
  confidence?: string | null;
  trialDesign?: string | null;
  trialLength?: string | null;
  results?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-papers".
 */
export interface ResearchPaper {
  id: number;
  URL: string;
  Label?: string | null;
  Product?: string | null;
  Supplement?: string | null;
  Year?: string | null;
  TLDR?: string | null;
  Effect?: string | null;
  Area?: string | null;
  BodyType?: string | null;
  Age?: string | null;
  Confidence?: string | null;
  AMEND?: boolean | null;
  FitnessCleaning?: boolean | null;
  CortisolExerciseCleaning?: boolean | null;
  MetaChecked?: boolean | null;
  NULL?: boolean | null;
  FundingNotes?: string | null;
  Source?: string | null;
  CreatedTime?: string | null;
  LastEditedTime?: string | null;
  FilesAndMedia?: string | null;
  NumberOfParticipants?: number | null;
  ParticipantsCortisol?: number | null;
  ParticipantsInflammation?: number | null;
  ParticipantsMuscleDamage?: number | null;
  ParticipantsMuscleSoreness?: number | null;
  ParticipantsOxidativeStress?: number | null;
  ParticipantsPain?: number | null;
  ParticipantsSleepQuality?: number | null;
  Participants?: string | null;
  StudiesCortisol?: number | null;
  StudiesInflammation?: number | null;
  StudiesMuscleDamage?: number | null;
  StudiesMuscleSoreness?: number | null;
  StudiesOxidativeStress?: number | null;
  StudiesPain?: number | null;
  StudiesSleepQuality?: number | null;
  RelatedToResults1?: string | null;
  RelatedToResults2?: string | null;
  Results?: string | null;
  Sex?: string | null;
  TrialDesign?: string | null;
  TrialLength?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'supplements';
        value: number | Supplement;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'research-papers';
        value: number | ResearchPaper;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplements_select".
 */
export interface SupplementsSelect<T extends boolean = true> {
  name?: T;
  dosage?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  gradeScore?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  linearScore?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  maxValues?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  sumValues?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  tldr?:
    | T
    | {
        cortisol?: T;
        inflammation?: T;
        muscleDamage?: T;
        muscleSoreness?: T;
        oxidativeStress?: T;
        pain?: T;
        sleepQuality?: T;
      };
  results?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  product?: T;
  supplement?: T;
  researchPaper?: T;
  mainTag?: T;
  subTag?: T;
  benefit?: T;
  benefitValue?: T;
  oxidativeStressFilter?: T;
  muscleDamageFilter?: T;
  muscleSorenessFilter?: T;
  inflammationFilter?: T;
  painFilter?: T;
  sleepQualityFilter?: T;
  cortisolFilter?: T;
  cortisolCleaning?: T;
  score?: T;
  participants?: T;
  age?: T;
  maxPain?: T;
  year?: T;
  sex?: T;
  bodyType?: T;
  confidence?: T;
  trialDesign?: T;
  trialLength?: T;
  results?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-papers_select".
 */
export interface ResearchPapersSelect<T extends boolean = true> {
  URL?: T;
  Label?: T;
  Product?: T;
  Supplement?: T;
  Year?: T;
  TLDR?: T;
  Effect?: T;
  Area?: T;
  BodyType?: T;
  Age?: T;
  Confidence?: T;
  AMEND?: T;
  FitnessCleaning?: T;
  CortisolExerciseCleaning?: T;
  MetaChecked?: T;
  NULL?: T;
  FundingNotes?: T;
  Source?: T;
  CreatedTime?: T;
  LastEditedTime?: T;
  FilesAndMedia?: T;
  NumberOfParticipants?: T;
  ParticipantsCortisol?: T;
  ParticipantsInflammation?: T;
  ParticipantsMuscleDamage?: T;
  ParticipantsMuscleSoreness?: T;
  ParticipantsOxidativeStress?: T;
  ParticipantsPain?: T;
  ParticipantsSleepQuality?: T;
  Participants?: T;
  StudiesCortisol?: T;
  StudiesInflammation?: T;
  StudiesMuscleDamage?: T;
  StudiesMuscleSoreness?: T;
  StudiesOxidativeStress?: T;
  StudiesPain?: T;
  StudiesSleepQuality?: T;
  RelatedToResults1?: T;
  RelatedToResults2?: T;
  Results?: T;
  Sex?: T;
  TrialDesign?: T;
  TrialLength?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}